context:
  version: "2.3.21"

package:
  name: kotlin
  version: ${{ version }}

source:
  url: https://github.com/JetBrains/kotlin/archive/v${{ version }}.tar.gz
  sha256: d060f5dc324e87e5b5580a41c0cc0489e77c78ca22f6cb4a2609d2206144b970

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk =21
  run:
    - openjdk

tests:
  - script:
      - kapt -help
      - kotlin -help
      - kotlinc -help

about:
  license: Apache-2.0
  license_file:
    - license/LICENSE.txt
    - license/third_party/
  summary: The Kotlin Programming Language.
  homepage: https://github.com/JetBrains/kotlin
  repository: https://github.com/JetBrains/kotlin

extra:
  recipe-maintainers:
    - danielnachun
