context:
  version: "2.3.20"

package:
  name: kotlin
  version: ${{ version }}

source:
  url: https://github.com/JetBrains/kotlin/archive/v${{ version }}.tar.gz
  sha256: 0de60619d72ea5b8e2f149c56c6566e7cae65b27bebb8c6d0e3b5436b9bcbe57

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk =21
  run:
    - openjdk

tests:
  - script:
      - kapt -help
      - kotlin -help
      - kotlinc -help

about:
  license: Apache-2.0
  license_file:
    - license/LICENSE.txt
    - license/third_party/
  summary: The Kotlin Programming Language.
  homepage: https://github.com/JetBrains/kotlin
  repository: https://github.com/JetBrains/kotlin

extra:
  recipe-maintainers:
    - danielnachun
