context:
  version: "2.4.10"

package:
  name: kotlin
  version: ${{ version }}

source:
  url: https://github.com/JetBrains/kotlin/archive/v${{ version }}.tar.gz
  sha256: b525ad1b56062509b3fbdf5f3c6e52eead999938cf1ba6c9129410699dba7414

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk =21
  run:
    - openjdk

tests:
  - script:
      - kapt -help
      - kotlin -help
      - kotlinc -help

about:
  license: Apache-2.0
  license_file:
    - license/LICENSE.txt
    - license/third_party/
  summary: The Kotlin Programming Language.
  homepage: https://github.com/JetBrains/kotlin
  repository: https://github.com/JetBrains/kotlin

extra:
  recipe-maintainers:
    - danielnachun
